AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An AWS Serverless Application that uses the ASP.NET Core framework running in
  Amazon Lambda.
Globals:
  Api:
    OpenApiVersion: 3.0.1
Parameters:
  Stage:
    Type: String
    Default: dev  
Resources:
  MyServerlessRestApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: !Sub ${Stage}  
  AspNetCoreFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'AWSServerless1::AWSServerless1.LambdaEntryPoint::FunctionHandlerAsync'
      Runtime: dotnetcore2.1
      CodeUri: 's3://cf-templates-xfgyhgphw5hc-us-east-1/serverless1.zip'
      MemorySize: 256
      Timeout: 30
      Role: null
      Policies:
        - AWSLambdaFullAccess
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
            RestApiId: !Ref MyServerlessRestApi  
        RootResource:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref MyServerlessRestApi
Outputs:
  ApiURL:
    Description: !Sub 'API endpoint URL for ${Stage} environment'
    Value: !Sub 'https://${MyServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/'